[global]
name="{{name}}"
node_id="{{node_id}}"
key="{{key}}"

[[trustees]]
name="donkey"
node_id="CHANGE"
key="{{key}}"

[[trustees]]
name="nas"
node_id="CHANGE"
key="{{key}}"

[[trustees]]
name="nas"
node_id="CHANGE"
key="{{key}}"

[[trustees]]
name="dev"
node_id="CHANGE"
key="{{key}}"

[[file_syncs]]
name="dotfiles"
path="~/.config"
[[file_syncs.target]]
mode="push-pull"
trustee="dev"
[[file_syncs.target]]
mode="push"
trustee="donkey"
[[file_syncs.target]]
mode="push"
trustee="nas"

[[file_syncs]]
name="work_laptop"
path="~/work"
[[file_syncs.target]]
mode="push"
trustee="donkey"
[[file_syncs.target]]
mode="push"
trustee="nas"

